import React from "react"
import type { ReactNode } from "react"
import type { Metadata } from "next"
import "./globals.css"
import { AuthProvider } from "@/context"

interface HomeLayoutProps {
  children: ReactNode
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function HomeLayout({ children }: HomeLayoutProps): JSX.Element {
  return (
    <html lang="en">
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  )
}
